namespace Weapons.Gun
{
    public enum Gunname
    {
        Default,
        FireBow,
        CrossBow,
        NatureWand,
        ExplodeFireWand,
        FreezeBow,
        NatureBow,
        Needle,
        FreezeStar,
        TrackGun,
        Red01,
        Red02,
        Red03,
        Red04,
        Red05,
        Yellow01,
        Yellow02,
        Yellow03,
        Yellow04,
        Yellow05,
        Blue01,
        Blue02,
        Blue03,
        Blue04,
        Blue05
    }
}